# Keys for LocalizationManger to use in source code: MIT License
# @author Vladimir Petrenko
@tool
class_name LocalizationKeys

const KEY = "KEY"
const KEY_PLAY = "KEY_PLAY"
const KEY_SETTINGS = "KEY_SETTINGS"
const KEY_LANGUAGE = "KEY_LANGUAGE"
const KEY_LANGUAGESELECT = "KEY_LANGUAGESELECT"
const KEY_BACK = "KEY_BACK"
const KEY_QUIT = "KEY_QUIT"
const KEY_PLAY_VIDEO = "KEY_PLAY_VIDEO"
const KEY_PLACEHOLDER = "KEY_PLACEHOLDER"
const KEY_VALUE = "KEY_VALUE"
const KEY_APPLY = "KEY_APPLY"
const KEY_PLACEHOLDER_AGE = "KEY_PLACEHOLDER_AGE"
const KEY_PLACEHOLDER_AGE_NAME = "KEY_PLACEHOLDER_AGE_NAME"
const ACTION_TEST_NAME = "ACTION_TEST_NAME"
const ACTION_EAT_NAME = "ACTION_EAT_NAME"
const ACTION_DRINK_NAME = "ACTION_DRINK_NAME"
const ACTION_COOK_NAME = "ACTION_COOK_NAME"
const PROPERTY_EXHAUSTION_NAME = "PROPERTY_EXHAUSTION_NAME"
const PROPERTY_EXHAUSTION_DISCRIPTION = "PROPERTY_EXHAUSTION_DISCRIPTION"
const PROPERTY_FATIGUE_NAME = "PROPERTY_FATIGUE_NAME"
const PROPERTY_FATIGUE_DISCRIPTION = "PROPERTY_FATIGUE_DISCRIPTION"
const PROPERTY_HUNGER_NAME = "PROPERTY_HUNGER_NAME"
const PROPERTY_HUNGER_DISCRIPTION = "PROPERTY_HUNGER_DISCRIPTION"
const PROPERTY_NONE_PROPERTY_NAME = "PROPERTY_NONE_PROPERTY_NAME"
const PROPERTY_NONE_PROPERTY_DISCRIPTION = "PROPERTY_NONE_PROPERTY_DISCRIPTION"
const PROPERTY_PSYCH_NAME = "PROPERTY_PSYCH_NAME"
const PROPERTY_PSYCH_DISCRIPTION = "PROPERTY_PSYCH_DISCRIPTION"
const PROPERTY_RADIATION_NAME = "PROPERTY_RADIATION_NAME"
const PROPERTY_RADIATION_DISCRIPTION = "PROPERTY_RADIATION_DISCRIPTION"
const PROPERTY_THIRST_NAME = "PROPERTY_THIRST_NAME"
const PROPERTY_THIRST_DISCRIPTION = "PROPERTY_THIRST_DISCRIPTION"
const EVENT_ACTION_DOTS_NAME = "EVENT_ACTION_DOTS_NAME"
const EVENT_ACTION_DOTS_DISCRIPTION = "EVENT_ACTION_DOTS_DISCRIPTION"
const EVENT_BS_DEFUALT_NAME = "EVENT_BS_DEFUALT_NAME"
const EVENT_BS_DEFUALT_START = "EVENT_BS_DEFUALT_START"
const EVENT_ACTION_SEARCH_NAME = "EVENT_ACTION_SEARCH_NAME"
const EVENT_ACTION_FINISH_NAME = "EVENT_ACTION_FINISH_NAME"
const EVENT_BS_FLOWERS_NAME = "EVENT_BS_FLOWERS_NAME"
const EVENT_BS_FLOWERS_START = "EVENT_BS_FLOWERS_START"
const EVENT_ACTION_COLLECT_SOME_NAME = "EVENT_ACTION_COLLECT_SOME_NAME"
const EVENT_ACTION_PASS_BY_NAME = "EVENT_ACTION_PASS_BY_NAME"
const EVENT_BS_FLOWERS_REWARD_1 = "EVENT_BS_FLOWERS_REWARD_1"
const EVENT_BS_EXIT = "EVENT_BS_EXIT"
const EVENT_BS_NOTHING_NAME = "EVENT_BS_NOTHING_NAME"
const EVENT_BS_NOTHING_START = "EVENT_BS_NOTHING_START"
const EVENT_BS_WOOD_1_NAME = "EVENT_BS_WOOD_1_NAME"
const EVENT_BS_WOOD_1_START = "EVENT_BS_WOOD_1_START"
const EVENT_BS_WOOD_1_REWARD = "EVENT_BS_WOOD_1_REWARD"
const EVENT_BS_WOOD_2_NAME = "EVENT_BS_WOOD_2_NAME"
const EVENT_BS_WOOD_2_START = "EVENT_BS_WOOD_2_START"
const EVENT_BS_WOOD_3_NAME = "EVENT_BS_WOOD_3_NAME"
const EVENT_BS_WOOD_3_START = "EVENT_BS_WOOD_3_START"
const EVENT_BS_WOOD_HOUSE_NAME = "EVENT_BS_WOOD_HOUSE_NAME"
const EVENT_BS_WOOD_HOUSE_START = "EVENT_BS_WOOD_HOUSE_START"
const EVENT_BS_ANIMAL_CORPSE_NAME = "EVENT_BS_ANIMAL_CORPSE_NAME"
const EVENT_BS_ANIMAL_CORPSE_START = "EVENT_BS_ANIMAL_CORPSE_START"
const ITEM_BUILDING_BONFIRE_NAME = "ITEM_BUILDING_BONFIRE_NAME"
const ITEM_BUILDING_BONFIRE_DISCRIPTION = "ITEM_BUILDING_BONFIRE_DISCRIPTION"
const ITEM_FOOD_CANNED_FOOD_NAME = "ITEM_FOOD_CANNED_FOOD_NAME"
const ITEM_FOOD_CANNED_FOOD_DISCRIPTION = "ITEM_FOOD_CANNED_FOOD_DISCRIPTION"
const ITEM_FOOD_FRESH_MEAT_NAME = "ITEM_FOOD_FRESH_MEAT_NAME"
const ITEM_FOOD_FRESH_MEAT_DISCRIPTION = "ITEM_FOOD_FRESH_MEAT_DISCRIPTION"
const ITEM_FOOD_FRY_MEAT_NAME = "ITEM_FOOD_FRY_MEAT_NAME"
const ITEM_FOOD_FRY_MEAT_DISCRIPTION = "ITEM_FOOD_FRY_MEAT_DISCRIPTION"
const ITEM_FOOD_WATER_CLEAR_NAME = "ITEM_FOOD_WATER_CLEAR_NAME"
const ITEM_FOOD_WATER_CLEAR_DISCRIPTION = "ITEM_FOOD_WATER_CLEAR_DISCRIPTION"
const ITEM_RESOURCE_DUCT_TAPE_NAME = "ITEM_RESOURCE_DUCT_TAPE_NAME"
const ITEM_RESOURCE_DUCT_TAPE_DISCRIPTION = "ITEM_RESOURCE_DUCT_TAPE_DISCRIPTION"
const ITEM_RESOURCE_FLINT_NAME = "ITEM_RESOURCE_FLINT_NAME"
const ITEM_RESOURCE_FLINT_DISCRIPTION = "ITEM_RESOURCE_FLINT_DISCRIPTION"
const ITEM_RESOURCE_STICK_NAME = "ITEM_RESOURCE_STICK_NAME"
const ITEM_RESOURCE_STICK_DISCRIPTION = "ITEM_RESOURCE_STICK_DISCRIPTION"
const ITEM_RESOURCE_WOOD_NAME = "ITEM_RESOURCE_WOOD_NAME"
const ITEM_RESOURCE_WOOD_DISCRIPTION = "ITEM_RESOURCE_WOOD_DISCRIPTION"
const ITEM_TOOL_HOMEMADE_AXE_NAME = "ITEM_TOOL_HOMEMADE_AXE_NAME"
const ITEM_TOOL_HOMEMADE_AXE_DISCRIPTION = "ITEM_TOOL_HOMEMADE_AXE_DISCRIPTION"
const ITEM_TOOL_HOMEMADE_KNIFE_NAME = "ITEM_TOOL_HOMEMADE_KNIFE_NAME"
const ITEM_TOOL_HOMEMADE_KNIFE_DISCRIPTION = "ITEM_TOOL_HOMEMADE_KNIFE_DISCRIPTION"
const ITEM_TOOL_PRIMUS_NAME = "ITEM_TOOL_PRIMUS_NAME"
const ITEM_TOOL_PRIMUS_DISCRIPTION = "ITEM_TOOL_PRIMUS_DISCRIPTION"
const ITEM_TOOL_SAUCEPAN_NAME = "ITEM_TOOL_SAUCEPAN_NAME"
const ITEM_TOOL_SAUCEPAN_DISCRIPTION = "ITEM_TOOL_SAUCEPAN_DISCRIPTION"
const SEARCH_DROP_NONE_NAME = "SEARCH_DROP_NONE_NAME"
const SEARCH_DROP_TEST_NAME = "SEARCH_DROP_TEST_NAME"
const SEARCH_DROP_FOREST_BIOME_NAME = "SEARCH_DROP_FOREST_BIOME_NAME"
const STRUCTURE_CROSSROAD_NAME = "STRUCTURE_CROSSROAD_NAME"
const STRUCTURE_CROSSROAD_DISCRIPTION = "STRUCTURE_CROSSROAD_DISCRIPTION"
const STRUCTURE_HOUSE_NAME = "STRUCTURE_HOUSE_NAME"
const STRUCTURE_HOUSE_DISCRIPTION = "STRUCTURE_HOUSE_DISCRIPTION"
const INVENTORY_TITLE = "INVENTORY_TITLE"
const LOCATION_TITLE = "LOCATION_TITLE"
const KEY_BUTTON_DROP = "KEY_BUTTON_DROP"
const KEY_BUTTON_PICKUP = "KEY_BUTTON_PICKUP"
const BIOME_GRASS_NAME = "BIOME_GRASS_NAME"
const BIOME_GRASS_DISCRIPTION = "BIOME_GRASS_DISCRIPTION"
const BIOME_FOREST_NAME = "BIOME_FOREST_NAME"
const BIOME_FOREST_DISCRIPTION = "BIOME_FOREST_DISCRIPTION"

const KEYS = [
 "KEY",
 "KEY_PLAY",
 "KEY_SETTINGS",
 "KEY_LANGUAGE",
 "KEY_LANGUAGESELECT",
 "KEY_BACK",
 "KEY_QUIT",
 "KEY_PLAY_VIDEO",
 "KEY_PLACEHOLDER",
 "KEY_VALUE",
 "KEY_APPLY",
 "KEY_PLACEHOLDER",
 "KEY_PLACEHOLDER_AGE",
 "KEY_PLACEHOLDER_AGE_NAME",
 "ACTION_TEST_NAME",
 "ACTION_EAT_NAME",
 "ACTION_DRINK_NAME",
 "ACTION_COOK_NAME",
 "PROPERTY_EXHAUSTION_NAME",
 "PROPERTY_EXHAUSTION_DISCRIPTION",
 "PROPERTY_FATIGUE_NAME",
 "PROPERTY_FATIGUE_DISCRIPTION",
 "PROPERTY_HUNGER_NAME",
 "PROPERTY_HUNGER_DISCRIPTION",
 "PROPERTY_NONE_PROPERTY_NAME",
 "PROPERTY_NONE_PROPERTY_DISCRIPTION",
 "PROPERTY_PSYCH_NAME",
 "PROPERTY_PSYCH_DISCRIPTION",
 "PROPERTY_RADIATION_NAME",
 "PROPERTY_RADIATION_DISCRIPTION",
 "PROPERTY_THIRST_NAME",
 "PROPERTY_THIRST_DISCRIPTION",
 "EVENT_ACTION_DOTS_NAME",
 "EVENT_ACTION_DOTS_DISCRIPTION",
 "EVENT_BS_DEFUALT_NAME",
 "EVENT_BS_DEFUALT_START",
 "EVENT_ACTION_SEARCH_NAME",
 "EVENT_ACTION_FINISH_NAME",
 "EVENT_BS_FLOWERS_NAME",
 "EVENT_BS_FLOWERS_START",
 "EVENT_ACTION_COLLECT_SOME_NAME",
 "EVENT_ACTION_PASS_BY_NAME",
 "EVENT_BS_FLOWERS_REWARD_1",
 "EVENT_BS_EXIT",
 "EVENT_BS_NOTHING_NAME",
 "EVENT_BS_NOTHING_START",
 "EVENT_BS_WOOD_1_NAME",
 "EVENT_BS_WOOD_1_START",
 "EVENT_BS_WOOD_1_REWARD",
 "EVENT_BS_WOOD_2_NAME",
 "EVENT_BS_WOOD_2_START",
 "EVENT_BS_WOOD_3_NAME",
 "EVENT_BS_WOOD_3_START",
 "EVENT_BS_WOOD_HOUSE_NAME",
 "EVENT_BS_WOOD_HOUSE_START",
 "EVENT_BS_ANIMAL_CORPSE_NAME",
 "EVENT_BS_ANIMAL_CORPSE_START",
 "ITEM_BUILDING_BONFIRE_NAME",
 "ITEM_BUILDING_BONFIRE_DISCRIPTION",
 "ITEM_FOOD_CANNED_FOOD_NAME",
 "ITEM_FOOD_CANNED_FOOD_DISCRIPTION",
 "ITEM_FOOD_FRESH_MEAT_NAME",
 "ITEM_FOOD_FRESH_MEAT_DISCRIPTION",
 "ITEM_FOOD_FRY_MEAT_NAME",
 "ITEM_FOOD_FRY_MEAT_DISCRIPTION",
 "ITEM_FOOD_WATER_CLEAR_NAME",
 "ITEM_FOOD_WATER_CLEAR_DISCRIPTION",
 "ITEM_RESOURCE_DUCT_TAPE_NAME",
 "ITEM_RESOURCE_DUCT_TAPE_DISCRIPTION",
 "ITEM_RESOURCE_FLINT_NAME",
 "ITEM_RESOURCE_FLINT_DISCRIPTION",
 "ITEM_RESOURCE_STICK_NAME",
 "ITEM_RESOURCE_STICK_DISCRIPTION",
 "ITEM_RESOURCE_WOOD_NAME",
 "ITEM_RESOURCE_WOOD_DISCRIPTION",
 "ITEM_TOOL_HOMEMADE_AXE_NAME",
 "ITEM_TOOL_HOMEMADE_AXE_DISCRIPTION",
 "ITEM_TOOL_HOMEMADE_KNIFE_NAME",
 "ITEM_TOOL_HOMEMADE_KNIFE_DISCRIPTION",
 "ITEM_TOOL_PRIMUS_NAME",
 "ITEM_TOOL_PRIMUS_DISCRIPTION",
 "ITEM_TOOL_SAUCEPAN_NAME",
 "ITEM_TOOL_SAUCEPAN_DISCRIPTION",
 "SEARCH_DROP_NONE_NAME",
 "SEARCH_DROP_TEST_NAME",
 "SEARCH_DROP_FOREST_BIOME_NAME",
 "STRUCTURE_CROSSROAD_NAME",
 "STRUCTURE_CROSSROAD_DISCRIPTION",
 "STRUCTURE_HOUSE_NAME",
 "STRUCTURE_HOUSE_DISCRIPTION",
 "INVENTORY_TITLE",
 "LOCATION_TITLE",
 "KEY_BUTTON_DROP",
 "KEY_BUTTON_PICKUP",
 "BIOME_GRASS_NAME",
 "BIOME_GRASS_DISCRIPTION",
 "BIOME_FOREST_NAME",
 "BIOME_FOREST_DISCRIPTION"
]
