# Keys for LocalizationManger to use in source code: MIT License
# @author Vladimir Petrenko
@tool
class_name LocalizationKeys

const KEY_NAME = "KEY_NAME"
const KEY_PLAY = "KEY_PLAY"
const KEY_SETTINGS = "KEY_SETTINGS"
const KEY_LANGUAGE = "KEY_LANGUAGE"
const KEY_LANGUAGESELECT = "KEY_LANGUAGESELECT"
const KEY_BACK = "KEY_BACK"
const KEY_QUIT = "KEY_QUIT"
const KEY_PLAY_VIDEO = "KEY_PLAY_VIDEO"
const KEY_PLACEHOLDER = "KEY_PLACEHOLDER"
const KEY_VALUE = "KEY_VALUE"
const KEY_APPLY = "KEY_APPLY"
const KEY_PLACEHOLDER_NAME = "KEY_PLACEHOLDER_NAME"
const KEY_PLACEHOLDER_AGE = "KEY_PLACEHOLDER_AGE"
const KEY_PLACEHOLDER_NAME_AGE = "KEY_PLACEHOLDER_NAME_AGE"
const ACTION_DISCRIPTION_TEST = "ACTION_DISCRIPTION_TEST"
const PROPERTY_NAME_EXHAUSTION = "PROPERTY_NAME_EXHAUSTION"
const PROPERTY_DISCRIPTION_EXHAUSTION = "PROPERTY_DISCRIPTION_EXHAUSTION"
const PROPERTY_NAME_FATIGUE = "PROPERTY_NAME_FATIGUE"
const PROPERTY_DISCRIPTION_FATIGUE = "PROPERTY_DISCRIPTION_FATIGUE"
const PROPERTY_NAME_HUNGER = "PROPERTY_NAME_HUNGER"
const PROPERTY_DISCRIPTION_HUNGER = "PROPERTY_DISCRIPTION_HUNGER"
const PROPERTY_NAME_NONE_PROPERTY = "PROPERTY_NAME_NONE_PROPERTY"
const PROPERTY_DISCRIPTION_NONE_PROPERTY = "PROPERTY_DISCRIPTION_NONE_PROPERTY"
const PROPERTY_NAME_PSYCH = "PROPERTY_NAME_PSYCH"
const PROPERTY_DISCRIPTION_PSYCH = "PROPERTY_DISCRIPTION_PSYCH"
const PROPERTY_NAME_RADIATION = "PROPERTY_NAME_RADIATION"
const PROPERTY_DISCRIPTION_RADIATION = "PROPERTY_DISCRIPTION_RADIATION"
const PROPERTY_NAME_THIRST = "PROPERTY_NAME_THIRST"
const PROPERTY_DISCRIPTION_THIRST = "PROPERTY_DISCRIPTION_THIRST"

const KEYS = [
 "KEY_NAME",
 "KEY_PLAY",
 "KEY_SETTINGS",
 "KEY_LANGUAGE",
 "KEY_LANGUAGESELECT",
 "KEY_BACK",
 "KEY_QUIT",
 "KEY_PLAY_VIDEO",
 "KEY_PLACEHOLDER",
 "KEY_VALUE",
 "KEY_APPLY",
 "KEY_PLACEHOLDER_NAME",
 "KEY_PLACEHOLDER_AGE",
 "KEY_PLACEHOLDER_NAME_AGE",
 "ACTION_DISCRIPTION_TEST",
 "PROPERTY_NAME_EXHAUSTION",
 "PROPERTY_DISCRIPTION_EXHAUSTION",
 "PROPERTY_NAME_FATIGUE",
 "PROPERTY_DISCRIPTION_FATIGUE",
 "PROPERTY_NAME_HUNGER",
 "PROPERTY_DISCRIPTION_HUNGER",
 "PROPERTY_NAME_NONE_PROPERTY",
 "PROPERTY_DISCRIPTION_NONE_PROPERTY",
 "PROPERTY_NAME_PSYCH",
 "PROPERTY_DISCRIPTION_PSYCH",
 "PROPERTY_NAME_RADIATION",
 "PROPERTY_DISCRIPTION_RADIATION",
 "PROPERTY_NAME_THIRST",
 "PROPERTY_DISCRIPTION_THIRST"
]